version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: atlas_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - atlas_network
    restart: unless-stopped
    # Optional MongoDB authentication
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=password

  atlas_service:
    build: .
    container_name: atlas_transparency_log
    depends_on:
      - mongodb
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      # Use mongodb with authentication if needed
      # - MONGODB_URI=mongodb://admin:password@mongodb:27017
      - KEY_PATH=/data/transparency_log_key.pem
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=${SERVER_PORT:-8080}
      - DB_NAME=atlas_manifests
      # Optional logging level
      - RUST_LOG=${RUST_LOG:-info}
    volumes:
      - key_data:/data
    networks:
      - atlas_network
    restart: unless-stopped
    # Healthcheck to ensure the service is properly running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-8080}/merkle/root"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  atlas_network:
    driver: bridge

volumes:
  mongodb_data:
  key_data: